### ISSUE TITLE
want change the color of the percent text

### ISSUE THREAD

**Issue by Dexilc** [loadingio/loading-bar#38]
can't change the color of the percent text,can u creat a api

**Comment by ceremcem** [comment]
You need the following CSS rule: 
```css
.ldBar-label:after {
    color: yellow;
}
```
